import type { CSSProperties } from "react";

/** Co-located styles for SkillsTab. */
export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 10, marginBottom: 12 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  count: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--accent)",
    background: "var(--accent-bg)",
    padding: "2px 8px",
    borderRadius: 5,
  } satisfies CSSProperties,
  filterInput: {
    width: "100%",
    fontSize: 13,
    padding: "8px 12px",
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    outline: "none",
    marginBottom: 10,
  } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", marginBottom: 14, lineHeight: 1.5 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 6, marginBottom: 20 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
    transition: "opacity .12s, border-color .12s, background .12s",
  } satisfies CSSProperties,
  rowDragging: { opacity: 0.45 } satisfies CSSProperties,
  rowDragOver: {
    border: "1px solid var(--accent)",
    background: "var(--accent-bg)",
  } satisfies CSSProperties,
  dragHandle: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 2,
    color: "var(--text-muted)",
    cursor: "grab",
    touchAction: "none",
  } satisfies CSSProperties,
  name: { fontSize: 13, fontWeight: 600, flex: 1 } satisfies CSSProperties,
  type: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-secondary)",
    background: "var(--bg-hover)",
    padding: "1px 8px",
    borderRadius: 4,
  } satisfies CSSProperties,
  moveButtons: { display: "flex", gap: 2 } satisfies CSSProperties,
  moveBtn: {
    display: "inline-flex",
    alignItems: "center",
    justifyContent: "center",
    padding: 4,
    borderRadius: 5,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
    color: "var(--text-muted)",
    cursor: "pointer",
  } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)", padding: "20px 0", textAlign: "center" } satisfies CSSProperties,
  saving: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,
} as const;
