import type { CSSProperties } from "react";

/** Co-located styles for ContextSection — mirrors the Agent editor's
 *  ContextTab row shape, minus drag/reorder chrome. */
export const s = {
  wrap: { maxWidth: 760 } satisfies CSSProperties,
  header: { display: "flex", alignItems: "center", gap: 10, marginBottom: 6 } satisfies CSSProperties,
  h2: { fontSize: 18, fontWeight: 700 } satisfies CSSProperties,
  count: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--accent-text)",
    background: "var(--accent-bg)",
    padding: "2px 8px",
    borderRadius: 5,
  } satisfies CSSProperties,
  subtitle: { fontSize: 13, color: "var(--text-secondary)", marginBottom: 12, lineHeight: 1.5 } satisfies CSSProperties,
  filterInput: {
    width: "100%",
    fontSize: 13,
    padding: "8px 12px",
    borderRadius: 7,
    border: "1px solid var(--border-strong)",
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
    outline: "none",
    marginBottom: 10,
  } satisfies CSSProperties,
  hint: { fontSize: 12, color: "var(--text-muted)", marginBottom: 14, lineHeight: 1.5 } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 6, marginBottom: 20 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "10px 12px",
    borderRadius: 7,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  rowMissing: { borderColor: "var(--warn)" } satisfies CSSProperties,
  path: { fontSize: 13, fontWeight: 600, flex: 1, wordBreak: "break-all" } satisfies CSSProperties,
  meta: { fontSize: 11, color: "var(--text-muted)" } satisfies CSSProperties,
  missingBadge: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--warn)",
    background: "var(--warn-bg)",
    padding: "1px 8px",
    borderRadius: 4,
  } satisfies CSSProperties,
  detachBtn: {
    fontSize: 11,
    fontWeight: 600,
    color: "var(--text-muted)",
    background: "transparent",
    border: "1px solid var(--border)",
    borderRadius: 5,
    padding: "3px 8px",
    cursor: "pointer",
  } satisfies CSSProperties,
  empty: { fontSize: 13, color: "var(--text-muted)", padding: "20px 0", textAlign: "center" } satisfies CSSProperties,
  noRepo: { fontSize: 13, color: "var(--text-muted)", padding: "20px 0" } satisfies CSSProperties,
  saving: { fontSize: 12, color: "var(--text-muted)" } satisfies CSSProperties,

  serializesAs: {
    marginTop: 8,
    padding: "14px 16px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-surface)",
  } satisfies CSSProperties,
  serializesTitle: {
    fontSize: 12,
    fontWeight: 700,
    color: "var(--text-muted)",
    textTransform: "uppercase",
    letterSpacing: "0.04em",
    marginBottom: 8,
  } satisfies CSSProperties,
  serializesHeading: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 13,
    fontWeight: 700,
    color: "var(--accent-text)",
    marginBottom: 6,
  } satisfies CSSProperties,
  serializesHint: { fontSize: 12, color: "var(--text-muted)", lineHeight: 1.5 } satisfies CSSProperties,
} as const;
