import type { CSSProperties } from "react";

/** Co-located styles for PrBriefCard. */
export const s = {
  body: { display: "flex", flexDirection: "column", gap: 14 } satisfies CSSProperties,
  metaRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    flexWrap: "wrap",
  } satisfies CSSProperties,
  listLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.06em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
    marginBottom: 6,
  } satisfies CSSProperties,
  skeletonStack: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  riskList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 8,
  } satisfies CSSProperties,
  riskItem: {
    display: "flex",
    flexDirection: "column",
    gap: 3,
    padding: 8,
    borderRadius: 8,
    background: "var(--bg-hover)",
  } satisfies CSSProperties,
  riskItemHeader: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  riskItemTitle: { fontSize: 12.5, fontWeight: 600, color: "var(--text-primary)" } satisfies CSSProperties,
  riskItemExplanation: { fontSize: 12, color: "var(--text-secondary)" } satisfies CSSProperties,
  riskItemFiles: {
    display: "flex",
    flexWrap: "wrap",
    gap: 6,
    marginTop: 2,
  } satisfies CSSProperties,
  noRisks: { fontSize: 12.5, color: "var(--text-muted)" } satisfies CSSProperties,
  focusList: {
    listStyle: "none",
    margin: 0,
    padding: 0,
    display: "flex",
    flexDirection: "column",
    gap: 3,
  } satisfies CSSProperties,
  focusItem: { fontSize: 12.5, color: "var(--text-secondary)" } satisfies CSSProperties,
  focusItemButton: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    fontSize: 12.5,
    color: "var(--accent)",
    background: "none",
    border: "none",
    padding: 0,
    cursor: "pointer",
    textAlign: "left",
  } satisfies CSSProperties,
  staleHint: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    padding: 8,
    borderRadius: 8,
    background: "var(--warn-bg)",
    color: "var(--warn)",
    fontSize: 12,
  } satisfies CSSProperties,
} as const;
